Fix build error exit
Signed-off-by: Eli Qiao <taget@linux.vnet.ibm.com>

diff --git a/build-node/build-node b/build-node/build-node
--- a/build-node/build-node
+++ b/build-node/build-node
@@ -49,8 +49,9 @@ cd ovirt-node
 ./autogen.sh --with-image-minimizer
 #EXTRA_RELEASE=.$USER$(date +%s) Not required if you're building an official build
 make publish
-if [ $? -eq 0 ]; then
-       exit 1
+if [ $? -ne 0 ]; then
+        echo "Error happend when building ovirt-node!!!"
+	exit 1
 fi
 echo "Build ovit-node-iso..."
 cd ../ovirt-node-iso
